Title: BioCypher python module configuration file

biocypher:
  offline: true
  user_schema_config_path: config/schema_config.yaml
  
neo4j:
  database_name: 'monarch'
  delimiter: "\t"
  array_delimiter: '|'
  quote_char: '"'

  multi_db: true
